# https://taskfile.dev

version: '3'

tasks:
  configure:
    cmds:
      - scripts/configure_env.sh
    desc: Configure environment
    sources:
      - scripts/configure_env.sh
    generates:
      - .env

  tfinit:
    cmds:
      - terraform init
    desc: Initialize Terraform
    deps: [configure]
    sources:
      - databricks.tf
      - main.tf
      - output.tf
      - provider.tf
    generates:
      - .terraform.lock.hcl

  apply:
    # bit of a hack here as taskfile.dev tool doesn't seem to be able to read .env file after it's been modified after task started...
    cmd: |
      echo "$TF_VAR_location"
      export $(grep -v '^#' .env | xargs)
      cat .env
      env|sort|grep TF_VAR
      echo "target location $TF_VAR_location"
      terraform apply -auto-approve
    desc: Apply Terraform
    deps: [tfinit]
    generates:
      - terraform.tfstate
    dotenv:
      - .env

  destroy:
    cmds:
      - terraform destroy -auto-approve
    prompt:
     - This will result in complete loss of the Storage Account just created and non-recoverable data loss... Do you want to continue?
     - Are you sure?
    desc: Destroy Terraform
    dotenv:
      - .env

  tidy:
    cmds:
      - rm -rf ./.terraform .task/ terraform.tfstate terraform.tfstate.backup .env .env.bak || true
    desc: Clean up
